### PR TITLE
Made code snippet tag text truncate if it's too long

### LINKED ISSUE #1395: Long tags in code snippet search overflows the button element
**Describe the issue**
Long tags in code snippet search overflows the button element when the side pane is narrower than the text

image

**To Reproduce**
1. Open the code snippet widget (click code snippets button on the side bar)
2. Either edit an existing snippet or create a new one
3. Add a tag with a long name and press enter to enable it
4. Save and close
5. Go back to the code snippet widget (side panel)
6. Click on the tag button to filter for tags
7. Check the long tag added 
8. Play with the side pane width (the problem happens on narrow states)

**Expected behavior**
The tag name should be contained in the button element, independent of the widget width.
If the full text can't fit, we could trim the end such as
`thisisanexampleofaverylongtag` --> `thisisanexample...`

**Environment information**
- Elyra version: 2.1.0rc2
- Operating system: MacOS
- Browser: Chrome

### PR DESCRIPTION
**Pull request by jdcai**
### What changes were proposed in this pull request?

If the code snippets tag text is too long then the text will be truncated so that it will fit within the code snippet window.
I also added a title attribute to the tag so that if it's truncated you can hover over the tag and see the full use text.
There was also an issue where if a tag starts with a space " test" a checkmark would not show up next to it when it's selected which was fixed by using textContent instead of innerHTML.

Before:
image
image

After:
image
image
image

### How was this pull request tested?

This was tested manually by adding tags to the code snippets window and selecting/unselecting them.
Useful tags for testing:
" wwwwwww wwwww wwwwwww wwwwww wwwwwww wwwww"
"wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww"
" test"
 
Fixes #1395

Developer's Certificate of Origin 1.1

       By making a contribution to this project, I certify that:

       (a) The contribution was created in whole or in part by me and I
           have the right to submit it under the Apache License 2.0; or

       (b) The contribution is based upon previous work that, to the best
           of my knowledge, is covered under an appropriate open source
           license and I have the right under that license to submit that
           work with modifications, whether created in whole or in part
           by me, under the same open source license (unless I am
           permitted to submit under a different license), as indicated
           in the file; or

       (c) The contribution was provided directly to me by some other
           person who certified (a), (b) or (c) and I have not modified
           it.

       (d) I understand and agree that this project and the contribution
           are public and that a record of the contribution (including all
           personal information I submit with it, including my sign-off) is
           maintained indefinitely and may be redistributed consistent with
           this project or the open source license(s) involved.

### CODE REVIEW

File: packages/metadata-common/src/FilterTools.tsx [hunk 1]
```diff
@@ -134,16 +136,17 @@ export class FilterTools extends React.Component<
...
-        {tag}
+        <span className={FILTER_TAG_LABEL}>{tag}</span>
       </button>
     );
   }
 
   handleClick(event: React.MouseEvent<HTMLButtonElement, MouseEvent>): void {
     const target = event.target as HTMLElement;
-    const clickedTag = target.innerText.trim();
+    const clickedTag = target.textContent ?? target.innerHTML;
```
Comment (karlaspuldaro) [inline packages/metadata-common/src/FilterTools.tsx:149]: Maybe using just `target.textContent` would solve the issue here, I don't see a case it would fall into `target.innerHTML`

Now that you pointed out to the whitespace bug I think we should clean whitespaces from both ends of a text when user registers a new tag. This can be a separate issue.

Comment (jdcai) [reply packages/metadata-common/src/FilterTools.tsx:149]: For textContent it can be null so I had to return a non null value in the case it is null. I think I could also do "" instead of target.innerHTML.

Comment (karlaspuldaro) [reply packages/metadata-common/src/FilterTools.tsx:149]: Ok, yeah maybe empty string as a fallback might be better then, otherwise `innerHTML` will always resolve to the new span element
`<span class=\"elyra-filter-tag-label\"> whitespace</span>`

Comment (jdcai) [reply packages/metadata-common/src/FilterTools.tsx]: okay I changed it to empty string

**Review by karlaspuldaro — APPROVED** [review]
Looks great! Thank you @jdcai

**Review by lresende — APPROVED** [review]
