### PR TITLE
Fix code snippet deletion bug

### LINKED ISSUE #736: Code snippet widget disappears
1.0.0 rc0

- Create and save a code snippet
- Click "Delete the code snippet" icon
- Click CANCEL (aka don't delete code snippet) - the widget listing code snippets disappears

image

### PR DESCRIPTION
**Pull request by marthacryan**
Fixes #736. Adds a boolean to indicate that the cancel button was clicked on delete. 
 
Developer's Certificate of Origin 1.1

       By making a contribution to this project, I certify that:

       (a) The contribution was created in whole or in part by me and I
           have the right to submit it under the Apache License 2.0; or

       (b) The contribution is based upon previous work that, to the best
           of my knowledge, is covered under an appropriate open source
           license and I have the right under that license to submit that
           work with modifications, whether created in whole or in part
           by me, under the same open source license (unless I am
           permitted to submit under a different license), as indicated
           in the file; or

       (c) The contribution was provided directly to me by some other
           person who certified (a), (b) or (c) and I have not modified
           it.

       (d) I understand and agree that this project and the contribution
           are public and that a record of the contribution (including all
           personal information I submit with it, including my sign-off) is
           maintained indefinitely and may be redistributed consistent with
           this project or the open source license(s) involved.

### CODE REVIEW

File: packages/code-snippet/src/CodeSnippetWidget.tsx [hunk 1]
```diff
@@ -213,19 +213,21 @@ class CodeSnippetDisplay extends React.Component<ICodeSnippetDisplayProps> {
         onClick: (): void => {
           CodeSnippetService.deleteCodeSnippet(codeSnippet).then(
             (response: any): void => {
```
Comment (ajbozarth) [inline packages/code-snippet/src/CodeSnippetWidget.tsx:215]: might be worth renaming this arg `deleted: boolean` (or something like that) for clarity

File: packages/code-snippet/src/CodeSnippetService.ts [hunk 2]
```diff
@@ -64,7 +64,7 @@ export class CodeSnippetService {
     return codeSnippetsByLanguage;
   }
 
-  static deleteCodeSnippet(codeSnippet: ICodeSnippet): Promise<void> {
+  static deleteCodeSnippet(codeSnippet: ICodeSnippet): Promise<boolean> {
```
Comment (ajbozarth) [inline packages/code-snippet/src/CodeSnippetService.ts:67]: I think it may also be worth adding a jsdoc comment for this function that clearly state the meaning of the boolean return
