### PR TITLE
Fix python editor output tab to be static

### LINKED ISSUE #635: Python code editor - console output "tab" should be static
If one runs a Python script the output is displayed in a "tab" on the canvas. This console log tab appears to be not a tab in the traditional sense that a user is supposed to move around. Currently one can move the tab, and if one does, the content is lost.

### PR DESCRIPTION
**Pull request by karlaspuldaro**
Fixes #635
 
Developer's Certificate of Origin 1.1

       By making a contribution to this project, I certify that:

       (a) The contribution was created in whole or in part by me and I
           have the right to submit it under the Apache License 2.0; or

       (b) The contribution is based upon previous work that, to the best
           of my knowledge, is covered under an appropriate open source
           license and I have the right under that license to submit that
           work with modifications, whether created in whole or in part
           by me, under the same open source license (unless I am
           permitted to submit under a different license), as indicated
           in the file; or

       (c) The contribution was provided directly to me by some other
           person who certified (a), (b) or (c) and I have not modified
           it.

       (d) I understand and agree that this project and the contribution
           are public and that a record of the contribution (including all
           personal information I submit with it, including my sign-off) is
           maintained indefinitely and may be redistributed consistent with
           this project or the open source license(s) involved.

### CODE REVIEW

File: packages/python-runner/src/PythonFileEditor.tsx [hunk 1]
```diff
@@ -131,7 +131,8 @@ export class PythonFileEditor extends DocumentWidget<
    */
   private createOutputAreaWidget = (): void => {
     // Add dockpanel wrapper for output area
-    this.dockPanel = new DockPanelSvg();
+    const dockPanelOptions: DockPanel.IOptions = { tabsMovable: false };
+    this.dockPanel = new DockPanelSvg(dockPanelOptions);
```
Comment (ajbozarth) [inline packages/python-runner/src/PythonFileEditor.tsx:135]: is there a reason we can't just do this "inline" like below and avoid an extra import?
```suggestion
    this.dockPanel = new DockPanelSvg({ tabsMovable: false });
```

Comment (karlaspuldaro) [reply packages/python-runner/src/PythonFileEditor.tsx]: I guess typescript got me used to define a type for everything 😄
