### PR TITLE
Metadata Editor and Widget Bug Fixes

### LINKED ISSUE #798: [Metadata editor regression?] Only first required property is checked by UI
1.0.0 rc3
I've noticed a UI behavior change that might be a regression:

- Create a new code snippet and enter only a name (there are more properties marked as required) OR
 create a new runtime and enter only a name (there are more properties marked as required)
- Previously the metadata editor would label each input field with "This field is required." (as shown for the name below)

image

- Click "save & close"

An error dialog is displayed:

```
Error making request
Validation failed for instance 'ddd' using the kfp schema with error: 'api_endpoint' is a required property.
Check the JupyterLab log for more details at 2020-08-03 09:11:19
```

For the sake of consistency the behavior should be the same for all input fields.

### LINKED ISSUE #802: [Fit and finish] Runtimes widget
- Display runtime type (e.g. Kubeflow Pipelines or Apache Airflow). While this might not seem that useful until another runtime is supported we should incorporate the information into the design.
 - Change "Runtime history" label to "Pipeline run history" since there isn't really a runtime history, only a pipeline run history.
image

### LINKED ISSUE #806: Runtimes widget disappears when no runtime is defined
1.0.0.rc3

- do not create a runtime

**Recreate 1:**

 - create a basic hello world notebook (any notebook will do)
 - create a new pipeline that includes the notebook
 - save the pipeline
 - click on the open runtimes button in the canvas
 - an error message is displayed ("no runtimes found")
  - the runtimes widget disappears

**Recreate 2:**
- Click on the runtimes icon on the left hand side

image

### LINKED ISSUE #814: [Fit and finish] Pipeline submission confirmation should display `display_name` instead of `name`
1.0.0. rc3

It appears that the runtime configuration name that the user enters in the UI (e.g. `def;ghi` or `abc def`) is used to generate a "safe" string that is used as an internal identifier , as seen in the output of the `list runtimes ...` command:

```
{
  "name": "defghi",
  "display_name": "def;ghi",
  "metadata": {
    "description": "hello",
    "api_endpoint": "http://...:31380/pipeline/",
    "cos_endpoint": "http://...:31671",
    "cos_username": "...",
    "cos_password": "...",
    "cos_bucket": "..."
  }
```

This identifier is displayed in the confirmation message instead of the display name.

image

### PR DESCRIPTION
**Pull request by ajbozarth**
Various Bug Fixes as a followup to #591

- Fixed required validation in MetadataEditor. Update to strict
equality check cause the `undefined` case to no longer be caught
by the `null` check
- Text updates to RuntimesWidget to clarify rutime type and api url
- Fixed support for RuntimeWidget when no runtimes are configured
- Focus on Name field when opening a Metadata Editor tab
- Update pipeline submission success dialog to use `display_name`

Fixes #798
Fixes #802
Fixes #806
Fixes #814 

 
Developer's Certificate of Origin 1.1

       By making a contribution to this project, I certify that:

       (a) The contribution was created in whole or in part by me and I
           have the right to submit it under the Apache License 2.0; or

       (b) The contribution is based upon previous work that, to the best
           of my knowledge, is covered under an appropriate open source
           license and I have the right under that license to submit that
           work with modifications, whether created in whole or in part
           by me, under the same open source license (unless I am
           permitted to submit under a different license), as indicated
           in the file; or

       (c) The contribution was provided directly to me by some other
           person who certified (a), (b) or (c) and I have not modified
           it.

       (d) I understand and agree that this project and the contribution
           are public and that a record of the contribution (including all
           personal information I submit with it, including my sign-off) is
           maintained indefinitely and may be redistributed consistent with
           this project or the open source license(s) involved.

### CODE REVIEW

File: packages/metadata-common/src/MetadataEditor.tsx [hunk 1]
```diff
@@ -123,7 +123,8 @@ export class MetadataEditor extends ReactWidget {
     for (const schemaField in this.schema) {
       if (
         this.requiredFields.includes(schemaField) &&
-        (this.metadata[schemaField] === null ||
+        (this.metadata[schemaField] === undefined ||
+          this.metadata[schemaField] === null ||
           this.metadata[schemaField] === '' ||
```
Comment (lresende) [inline packages/metadata-common/src/MetadataEditor.tsx:128]: What if you do something like  `&& (this.metadata[schemaField] || this.metadata[schemaField] === '(No selection)')` where the first comparison should take care of null, undefined and empty string

Comment (kevin-bates) [reply packages/metadata-common/src/MetadataEditor.tsx:128]: How about a local function `this.is_field_set(schemaField: str): boolean`?  Seems like there are way too many variations to deal with.

Comment (ajbozarth) [reply packages/metadata-common/src/MetadataEditor.tsx:128]: @lresende we can't do that because 0 or false may be valid and are also considered falsy when evaluating `this.metadata[schemaField]`, also `[]` is considered truthy. I do like the idea of a separate function like @kevin-bates suggested, I'll do that.

Comment (ajbozarth) [reply packages/metadata-common/src/MetadataEditor.tsx]: pushed an update

File: packages/metadata-common/src/MetadataEditor.tsx [hunk 2]
```diff
@@ -110,6 +110,16 @@ export class MetadataEditor extends ReactWidget {
...
 
+  private isFieldEmpty(schemaField: any): boolean {
+    return (
+      schemaField === undefined ||
+      schemaField === null ||
+      schemaField === '' ||
+      schemaField === [] ||
+      schemaField === '(No selection)'
+    );
+  }
```
Comment (kevin-bates) [inline packages/metadata-common/src/MetadataEditor.tsx:121]: The way this is implemented, it's not necessary to be a class method but works.  I figured it would act on `this.metadata` and take the field name as a parameter.  

If we could at least change the parameter name to `schemaValue` then that might eliminate some potential confusion.  But then the question arises - should this be named `IsValueEmpty()`?  :smile:

Comment (ajbozarth) [reply packages/metadata-common/src/MetadataEditor.tsx:121]: this would be a good function to put in a util, but I didn't think it was worth creating a util.ts just for this function (thus making it a private class method).

As for naming, you are correct, based on my current implementation it should be value not field. I'll push an update promptly

**Comment by ptitzler** [comment]
@ajbozart just noticed a regression. The tool tip used to be correct.


image

**Comment by ajbozarth** [comment]
Pushed an update that addressed the following issues @ptitzler raised:

- Focus on Name field when opening a Metadata Editor (including switching between tabs)
- Fixed race condition causing `Create new undefined` tooltip
- Fixed #814

File: packages/metadata-common/src/MetadataEditor.tsx [hunk 3]
```diff
@@ -110,6 +114,16 @@ export class MetadataEditor extends ReactWidget {
     this.update();
   }
 
+  private isValueEmpty(schemaValue: any): boolean {
+    return (
+      schemaValue === undefined ||
+      schemaValue === null ||
+      schemaValue === '' ||
```
Comment (karlaspuldaro) [inline packages/metadata-common/src/MetadataEditor.tsx:121]: We can just use `!schemaValue` instead of these 3 value checks

File: packages/metadata-common/src/MetadataEditor.tsx [hunk 4]
```diff
@@ -110,6 +114,16 @@ export class MetadataEditor extends ReactWidget {
...
+      schemaValue === [] ||
```
Comment (karlaspuldaro) [inline packages/metadata-common/src/MetadataEditor.tsx:122]: This is probably not gonna work since an array is an object, if we do [] === [] we get `false`
To be safe, we could do `Array.isArray(schemaValue) && schemaValue.length`

File: packages/metadata-common/src/MetadataEditor.tsx (hunk 3 above)
Comment (ajbozarth) [reply packages/metadata-common/src/MetadataEditor.tsx:121]: I mentioned this in a review comment from Luciano but we can't use that because it would evaluate 0 and false as falsy as well, but those might be valid content.

File: packages/metadata-common/src/MetadataEditor.tsx (hunk 4 above)
Comment (ajbozarth) [reply packages/metadata-common/src/MetadataEditor.tsx:122]: nice catch, I'll make that change

**Comment by marthacryan** [comment]
Tried locally and it worked as expected for all of the issues mentioned. LGTM
