### PR TITLE
Validate numeric fields in submit file dialog

### LINKED ISSUE #1516: Submit notebook/script dialog validation can be improved
**Describe the issue**
The submit feature for notebooks and scripts does not validate its dialog input fields.
image

Compared to the Pipeline Editor validation:

**To Reproduce**
1. Open a notebook or script editor
2. click the submit button
3. Add a negative value to the CPU field
4. The `Ok` button is still enabled

**Expected behavior**
The `Ok` button should be disabled should the user type an invalid input to any field

**Deployment information**
Describe what you've deployed and how:
 - Elyra version: 2.2.1
 - Operating system: MacOS
 - Installation source: PyPI (in a conda environment)
- Browser: Chrome

### PR DESCRIPTION
**Pull request by karlaspuldaro**
Fixes #1516 
The file submit dialog only validates fields marked as required.
This PR adds a validator for non-required numeric fields in the UI.

### What changes were proposed in this pull request?
Added validation for numeric fields in submit file dialog. If the input is negative, disable the OK button
image

Also added descriptions to those resources fields to be consistent with pipeline node properties display.

### How was this pull request tested?
Manual testing for invalid input from the keyboard, invalid input using the up/down arrows in the UI.
Checked pipeline run/submit dialog validation haven't changed.

Developer's Certificate of Origin 1.1

       By making a contribution to this project, I certify that:

       (a) The contribution was created in whole or in part by me and I
           have the right to submit it under the Apache License 2.0; or

       (b) The contribution is based upon previous work that, to the best
           of my knowledge, is covered under an appropriate open source
           license and I have the right under that license to submit that
           work with modifications, whether created in whole or in part
           by me, under the same open source license (unless I am
           permitted to submit under a different license), as indicated
           in the file; or

       (c) The contribution was provided directly to me by some other
           person who certified (a), (b) or (c) and I have not modified
           it.

       (d) I understand and agree that this project and the contribution
           are public and that a record of the contribution (including all
           personal information I submit with it, including my sign-off) is
           maintained indefinitely and may be redistributed consistent with
           this project or the open source license(s) involved.

### CODE REVIEW

**Review by akchinSTC — APPROVED** [review]
Tested and looks good to me.

File: packages/ui-components/src/FormDialog.tsx [hunk 1]
```diff
@@ -108,6 +103,27 @@ export const showFormDialog = async (
           requiredFields,
           defaultButton
         );
+      } else {
```
Comment (lresende) [inline packages/ui-components/src/FormDialog.tsx:106]: Should we actually enhance the `handleSingleFieldValidation` logic instead of creating this additional one?

**Review by lresende — CHANGES_REQUESTED** [review]
See comments above.

File: packages/ui-components/src/FormDialog.tsx (hunk 1 above)
Comment (karlaspuldaro) [reply packages/ui-components/src/FormDialog.tsx]: @lresende good idea, I took the opportunity to refactor the entire flow now that the validation is not just done for required fields, making the code simpler. `handleSingleFieldValidation` is also enhanced as suggested and now called `isFieldValid`.

**Review by marthacryan — APPROVED** [review]
Haven't tested locally but the code LGTM. Thanks!
