### PR TITLE
Fix flaky integration test

### LINKED ISSUE #2638: Script editor CI tests are flaky
**Describe the issue**
Some tests that require typing some code to the script editor causes the lsp code assistant box to pop up, hiding the  editor toolbar buttons. Whenever the next step is to click `Run as Pipeline` button tests fail since cypess cannot find the element.

image

A previous workaround was to add a new line to the text, although this not always seems to work (many times need to re-run CI job).

**Expected behavior**
Correctly dismiss the code assistant box (pressing escape would be an option).

**Context information**
 - Elyra version: v3.8.0-dev
 - Installation source: from src
 - Deployment type: local
 - Operating system: macOS

### PR DESCRIPTION
**Pull request by karlaspuldaro**
Fixes #2638

### What changes were proposed in this pull request?
Remove the original work around of adding a new line to the text editor. 
Add `esc` type command to dismiss the code assistant.

### How was this pull request tested?
Run script editor tests passes locally and should also pass CI.
 
Developer's Certificate of Origin 1.1

       By making a contribution to this project, I certify that:

       (a) The contribution was created in whole or in part by me and I
           have the right to submit it under the Apache License 2.0; or

       (b) The contribution is based upon previous work that, to the best
           of my knowledge, is covered under an appropriate open source
           license and I have the right under that license to submit that
           work with modifications, whether created in whole or in part
           by me, under the same open source license (unless I am
           permitted to submit under a different license), as indicated
           in the file; or

       (c) The contribution was provided directly to me by some other
           person who certified (a), (b) or (c) and I have not modified
           it.

       (d) I understand and agree that this project and the contribution
           are public and that a record of the contribution (including all
           personal information I submit with it, including my sign-off) is
           maintained indefinitely and may be redistributed consistent with
           this project or the open source license(s) involved.

### CODE REVIEW

File: tests/integration/scripteditor.ts [hunk 1]
```diff
@@ -89,7 +89,10 @@ describe('Script Editor tests', () => {
     cy.createNewScriptEditor('Python');
 
     // Add some text to the editor
-    cy.get('span[role="presentation"]').type('print("test")\n');
+    cy.get('span[role="presentation"]').type('print("test")');
+
+    cy.wait(1000);
```
Comment (ajbozarth) [inline tests/integration/scripteditor.ts:94]: is a full second necessary or would 500 ms do instead? I'm just worried about adding more waits.

**Review by ajbozarth — APPROVED** [review]
LGTM, just one non-blocking question about the wait length

File: tests/integration/scripteditor.ts (hunk 1 above)
Comment (karlaspuldaro) [reply tests/integration/scripteditor.ts:94]: It was arbitrary, I can try 500

**Review by lresende — APPROVED** [review]
