### PR TITLE
Reduce the number of duplicate calls to backend services

### LINKED ISSUE #1750: 2.3/rc1 Improve console log messages related to component initialization
**Describe the issue**
A clear and concise description of what the issue is
- Most of these messages should probably be debug messages
- Messages should not be duplicated
   ```
   Retrieving pipeline component properties for component r-script
   Retrieving pipeline component properties for component r-script
   ```
- Messages could be less verbose and indicate the associated runtime type
   ```
    Retrieving pipeline component properties for component r-script
   ```

**To Reproduce**
1. Start JL and inspect the console output

<pre>
[I 2021-06-11 11:02:59.962 ServerApp] Retrieving pipeline components for airflow
[I 2021-06-11 11:02:59.963 ServerApp] Retrieving pipeline components for local
[I 2021-06-11 11:02:59.965 ServerApp] Retrieving pipeline components for airflow
[I 2021-06-11 11:02:59.985 ServerApp] Retrieving pipeline component properties for component notebooks
[I 2021-06-11 11:02:59.990 ServerApp] Retrieving pipeline component properties for component python-script
[I 2021-06-11 11:02:59.994 ServerApp] Retrieving pipeline component properties for component r-script
[I 2021-06-11 11:03:02.685 ServerApp] Retrieving pipeline component properties for component notebooks
[I 2021-06-11 11:03:02.687 ServerApp] Retrieving pipeline component properties for component notebooks
[I 2021-06-11 11:03:02.689 ServerApp] Retrieving pipeline component properties for component python-script
[I 2021-06-11 11:03:02.691 ServerApp] Retrieving pipeline component properties for component python-script
[I 2021-06-11 11:03:02.694 ServerApp] Retrieving pipeline component properties for component r-script
[I 2021-06-11 11:03:02.696 ServerApp] Retrieving pipeline component properties for component r-script
[I 2021-06-11 11:03:02.698 ServerApp] Retrieving pipeline component properties for component bash-operator
[I 2021-06-11 11:03:02.782 ServerApp] Retrieving pipeline component properties for component bash-operator
[I 2021-06-11 11:03:02.889 ServerApp] Retrieving pipeline component properties for component docker-operator
[I 2021-06-11 11:03:02.960 ServerApp] Retrieving pipeline component properties for component docker-operator
[I 2021-06-11 11:03:03.038 ServerApp] Retrieving pipeline component properties for component email-operator
[I 2021-06-11 11:03:03.102 ServerApp] Retrieving pipeline component properties for component email-operator
[I 2021-06-11 11:03:03.169 ServerApp] Retrieving pipeline component properties for component http-operator
[I 2021-06-11 11:03:03.229 ServerApp] Retrieving pipeline component properties for component http-operator
[I 2021-06-11 11:03:03.284 ServerApp] Retrieving pipeline component properties for component kubernetes-pod-operator
[I 2021-06-11 11:03:03.393 ServerApp] Retrieving pipeline component properties for component kubernetes-pod-operator
[I 2021-06-11 11:03:03.450 ServerApp] Retrieving pipeline component properties for component spark-jdbc-operator
[I 2021-06-11 11:03:03.562 ServerApp] Retrieving pipeline component properties for component spark-jdbc-operator
[I 2021-06-11 11:03:03.645 ServerApp] Retrieving pipeline component properties for component spark-sql-operator
[I 2021-06-11 11:03:03.713 ServerApp] Retrieving pipeline component properties for component spark-sql-operator
[I 2021-06-11 11:03:03.782 ServerApp] Retrieving pipeline component properties for component spark-submit-operator
[I 2021-06-11 11:03:03.846 ServerApp] Retrieving pipeline component properties for component spark-submit-operator
[I 2021-06-11 11:03:03.950 ServerApp] Retrieving pipeline component properties for component ssh-operator
[I 2021-06-11 11:03:04.012 ServerApp] Retrieving pipeline component properties for component ssh-operator
</pre>

### PR DESCRIPTION
**Pull request by bourdakos1**
This PR is intended to fix the CI timeout issue, but should also fix #1750

[SWR](https://swr.vercel.app/) is a react library with a lot of really nice data fetching features. One of these features is request deduplication. This means if you have several components making a request for the same information or if your components are rerendering too often, it will only make one http request and share the response across all components.

The log duplication is from request duplication so SWR should resolve that out of the box. I believe the CI issue and duplicated requests are a bit of a side effect of the react `useEffect` hook being a bit tricky to master. Using SWR should alleviate us from needing to rely on `useEffect` so hopefully less bugs like this in the future

### CODE REVIEW

**Comment by kevin-bates** [comment]
Thanks @bourdakos1. Could you please update the opening description with a brief description of what SWR is and how it might address the CI and log duplication issue?  Although I'm clueless about the technologies used in the frontend, it might be helpful to myself and others to get an idea of how this will help.  Thanks.

**Comment by lresende** [comment]
On the same line as @kevin-bates, could we actually change the title of the PR to what is actually trying to do, something more like `Reduce the number of duplicate calls to backend services`. 

Also, we have a similar utility that is supposed to handle the calls to backends (@ajbozarth knows that very well). Could you guys collaborate to make sure we don't create two utilities for the same thing.

File: packages/services/src/requests.ts [hunk 1]
```diff
@@ -39,10 +39,10 @@ export class RequestHandler {
    * @returns a promise that resolves with the server response on success or
    * an error dialog result in cases of failure.
    */
-  static async makeGetRequest(
+  static async makeGetRequest<T = any>(
```
Comment (ajbozarth) [inline packages/services/src/requests.ts:42]: If this is the only change here we should just update all the functions in this class to match

File: packages/pipeline-editor/src/pipeline-hooks.ts [hunk 2]
```diff
@@ -0,0 +1,201 @@
...
+
+interface IRuntimeImage {
+  name: string;
+  display_name: string;
+  metadata: {
+    image_name: string;
+  };
+}
+
+export const useRuntimeImages = <T = IRuntimeImagesResponse>(): IReturn<T> => {
```
Comment (ajbozarth) [inline packages/pipeline-editor/src/pipeline-hooks.ts:46]: IIUC this is replacing `PipelineService.getRuntimes` but it removing the error handling in that function?

**Review by ajbozarth — COMMENTED** [review]
I still (after our Webex) think that the contents of pipeline-hooks belongs in PipelineService rather than a new file. especially since parts of it are straight replace functionality found there.

Though I dont think it should be done in a follow up, I will relent to moving the functionality there in our followup cleanup PR when we remove the dead code in PipelineService if we want this in quick

File: packages/pipeline-editor/src/pipeline-hooks.ts (hunk 2 above)
Comment (bourdakos1) [reply packages/pipeline-editor/src/pipeline-hooks.ts:46]: oh yea, so I should reject if the array is empty? I also missed the sorting

Comment (ajbozarth) [reply packages/pipeline-editor/src/pipeline-hooks.ts:46]: we should keep the same functionality, but based on my understanding of swr from this PR should we not just put the swr functionality in the MetadataService rather than bypassing it? then any calls to it would just be supported, or is it not that simple?

**Comment by bourdakos1** [comment]
@ajbozarth I switched to using the metadata service directly. For the error, we can't really do what we are doing now (we could but not recommended) 

I know we are replacing error dialogs with toasts in the future, do you have more details on how that would work?

**Comment by ajbozarth** [comment]
For the error messages we plan to move the non-interactive error message to toast, so any dialog that has a stack trace, links, or buttons other than close would stay dialogs (at least that's the initial plan)

**Comment by karlaspuldaro** [comment]
Since this PR is also cleaning up log messages, I guess we can remove this line:
https://github.com/elyra-ai/elyra/blob/59d3eeb4ca2dd18bf2c678eab312c168287f0cac/packages/pipeline-editor/src/PipelineEditorWidget.tsx#L608
to avoid unnecessary logs like
image

**Review by ajbozarth — APPROVED** [review]
Based on our Webex discussion let merge this as is and handle the duplicate code and other issues with the service to a followup refactor Issue
