### PR TITLE
Fix common properties bug

### LINKED ISSUE #1493: Properties copy over from one node to another when switching properties editor
**Describe the issue**
Properties copy over from one node to another when switching properties editor (i.e. properties editor is open and new node is selected in pipeline editor).

**To Reproduce**
1. Drag file onto pipeline editor
2. Drag a different file onto pipeline editor
3. Open properties editor
4. Select one of the nodes
5. Select the other node
6. Select the first node again
7. The filename for the first node is now the filename of the second node.

### PR DESCRIPTION
**Pull request by marthacryan**
Fixes #1493. The properties editor has a bug that causes properties to copy over to a different node when a new node is selected in the pipeline editor. This PR adds logic to apply the properties changes as they happen instead of when switching nodes to prevent that from happening. 
 
Developer's Certificate of Origin 1.1

       By making a contribution to this project, I certify that:

       (a) The contribution was created in whole or in part by me and I
           have the right to submit it under the Apache License 2.0; or

       (b) The contribution is based upon previous work that, to the best
           of my knowledge, is covered under an appropriate open source
           license and I have the right under that license to submit that
           work with modifications, whether created in whole or in part
           by me, under the same open source license (unless I am
           permitted to submit under a different license), as indicated
           in the file; or

       (c) The contribution was provided directly to me by some other
           person who certified (a), (b) or (c) and I have not modified
           it.

       (d) I understand and agree that this project and the contribution
           are public and that a record of the contribution (including all
           personal information I submit with it, including my sign-off) is
           maintained indefinitely and may be redistributed consistent with
           this project or the open source license(s) involved.

### CODE REVIEW

File: packages/pipeline-editor/src/PipelineEditorWidget.tsx [hunk 1]
```diff
@@ -568,67 +565,49 @@ export class PipelineEditor extends React.Component<
   }
 
   propertyListener(data: any): void {
+    console.log(data);
```
Comment (bourdakos1) [inline packages/pipeline-editor/src/PipelineEditorWidget.tsx:568]: log

**Comment by bourdakos1** [comment]
The original issue is now fixed. However, there is still a similar issue with the array items. I'm guessing the custom component isn't fully controlled and doesn't trigger `UPDATE_PROPERTY` for every change

**Comment by bourdakos1** [comment]
I think this needs to be `value` not `defaultValue`, but changing this will probably break other things: https://github.com/marthacryan/elyra/blob/c3cecbd7580aae637e0c27b65aa2b0c9ec546ed4/packages/pipeline-editor/src/StringArrayInput.tsx#L88

**Comment by bourdakos1** [comment]
I think we can fix this issue separately. This doesn't effect the underlying data, just a rendering bug

**Review by bourdakos1 — APPROVED** [review]

**Comment by marthacryan** [comment]
> The original issue is now fixed. However, there is still a similar issue with the array items. I'm guessing the custom component isn't fully controlled and doesn't trigger `UPDATE_PROPERTY` for every change

Could you add the steps to reproduce? I tried and couldn't figure out how to reproduce

**Comment by bourdakos1** [comment]
oh yea sorry, It's similar to the previous issue:
- open properties
- add an item to a list (for example `1`)
- click on another node and add an item to a list (for example `2`)
- click anywhere on the canvas
- reopen the node properties where you entered `2` and it should incorrectly say `1`
