### PR TITLE
Fix code snippet language check

### LINKED ISSUE #2018: Adding a code snippet into a script editor does not trigger language check
**Describe the issue**
Regression - Adding a code snippet into a script editor does not trigger language check. 
It still works as expected on notebooks.

After a quick investigation, looks like the widget class names are being mapped to something else during runtime, so [this statement](https://github.com/elyra-ai/elyra/blob/db8f0db786b580cfa2080bd788fc1df11dd8ad3e/packages/code-snippet/src/CodeSnippetWidget.tsx#L126) that checks for script editor is never true.

**To Reproduce**
1. Open a Python or R Editor
2. Open the code snippets tab
4. Click the insert button on the snippet item (Make sure to pick a code snippet of a language different from the open editor)
5. Notice the snippet is automatically added to the editor without displaying a warning dialog

**Expected behavior**
Language check should be triggered and display a warning when there is a language mismatch when inserting a code snippet into a script editor

**Context information**:
 - Elyra version: 3.0.0
 - Operating system: macos
 - Browser: Chrome

### PR DESCRIPTION
**Pull request by karlaspuldaro**
Fix code snippet language check when inserting into script editors using the `insert` button.
Fixes #2018 

### What changes were proposed in this pull request?
When the package is published - eg. not installed from source - widget names are mapped to some kind of id. 
This is (probably) why when installing elyra/code-snippets extension from `pip` or `conda` the condition 
`if (widget.constructor.name === 'ScriptEditor')` fails, and language check is never triggered.Although it works as expected when installing from source code.

This PR removes the reference to ScriptEditor widget, which means the code-snippet extension will verify language match against any file editor which has kernel language support (such as Elyra Python/R editors).

**NOTE**: It won't change the behavior from source installation, proper fix would only be verified on a new publishing including these changes (or is there a way to mock that environment?)

### How was this pull request tested?
New integration tests added.
Includes small refactor/cleanup of existing relevant tests.
 
Developer's Certificate of Origin 1.1

       By making a contribution to this project, I certify that:

       (a) The contribution was created in whole or in part by me and I
           have the right to submit it under the Apache License 2.0; or

       (b) The contribution is based upon previous work that, to the best
           of my knowledge, is covered under an appropriate open source
           license and I have the right under that license to submit that
           work with modifications, whether created in whole or in part
           by me, under the same open source license (unless I am
           permitted to submit under a different license), as indicated
           in the file; or

       (c) The contribution was provided directly to me by some other
           person who certified (a), (b) or (c) and I have not modified
           it.

       (d) I understand and agree that this project and the contribution
           are public and that a record of the contribution (including all
           personal information I submit with it, including my sign-off) is
           maintained indefinitely and may be redistributed consistent with
           this project or the open source license(s) involved.

### CODE REVIEW

File: packages/code-snippet/src/CodeSnippetWidget.tsx [hunk 1]
```diff
@@ -178,6 +179,15 @@ class CodeSnippetDisplay extends MetadataDisplay<
     return (widget as DocumentWidget).content instanceof FileEditor;
   };
 
+  // Return the language of the editor or empty string
+  private getEditorLanguage = (
+    widget: DocumentWidget<FileEditor>
+  ): string | undefined => {
+    const editorLanguage =
+      widget.context.sessionContext.kernelPreference.language;
+    return editorLanguage === 'null' ? '' : editorLanguage;
```
Comment (ajbozarth) [inline packages/code-snippet/src/CodeSnippetWidget.tsx:188]: is there a reason you're checking for the string containing null here now instead of checking for undefined?

Comment (karlaspuldaro) [reply packages/code-snippet/src/CodeSnippetWidget.tsx:188]: Yes. Plain text editors will have this field set to null as a string.

**Review by marthacryan — APPROVED** [review]
Tried locally and it seems to be working well! I didn't do too thorough of a code review but it looks good to me. Thanks!

**Review by ajbozarth — APPROVED** [review]
As mentioned in todays dev meeting, the code LGTM, but I have not had time to test it locally
