### PR TITLE
Fix checkbox display in pipeline export dialog

### LINKED ISSUE #1106: Pipeline export dialog checkbox not working
When exporting a pipeline, the checkbox to the field `Replace if file already exists` looks off and doesn't allow being checked anymore.

image

### PR DESCRIPTION
**Pull request by karlaspuldaro**
Fixes #1106 
After changes:
image

Developer's Certificate of Origin 1.1

       By making a contribution to this project, I certify that:

       (a) The contribution was created in whole or in part by me and I
           have the right to submit it under the Apache License 2.0; or

       (b) The contribution is based upon previous work that, to the best
           of my knowledge, is covered under an appropriate open source
           license and I have the right under that license to submit that
           work with modifications, whether created in whole or in part
           by me, under the same open source license (unless I am
           permitted to submit under a different license), as indicated
           in the file; or

       (c) The contribution was provided directly to me by some other
           person who certified (a), (b) or (c) and I have not modified
           it.

       (d) I understand and agree that this project and the contribution
           are public and that a record of the contribution (including all
           personal information I submit with it, including my sign-off) is
           maintained indefinitely and may be redistributed consistent with
           this project or the open source license(s) involved.

### CODE REVIEW

File: packages/pipeline-editor/src/PipelineExportDialog.tsx [hunk 1]
```diff
@@ -60,7 +60,12 @@ export class PipelineExportDialog extends React.Component<IProps> {
             </option>
           ))}
         </select>
-        <input type="checkbox" id="overwrite" name="overwrite" />
+        <input
+          type="checkbox"
+          id="overwrite"
+          name="overwrite"
+          style={{ appearance: 'auto', height: 'auto' }}
+        />
```
Comment (lresende) [inline packages/pipeline-editor/src/PipelineExportDialog.tsx:68]: Is there a way we can make this global in a CSS? otherwise, you will need to fix it in `submit notebook` and possibly on the node property dialog box.

Comment (karlaspuldaro) [reply packages/pipeline-editor/src/PipelineExportDialog.tsx:68]: Yes, good point, I thought this was the only checkbox affected. The one in node properties look good, but you're right, we have the same issue in `submit notebook`.

File: packages/pipeline-editor/style/index.css [hunk 2]
```diff
@@ -179,3 +179,8 @@ span.elyra-BreadCrumbs-disabled svg path.jp-icon3[fill] {
 span.elyra-BreadCrumbs-disabled + span {
   color: var(--md-grey-500);
 }
+
+input.elyra-Dialog-checkbox {
```
Comment (ajbozarth) [inline packages/pipeline-editor/style/index.css:183]: nit: why capitalize Dialog here?

Comment (karlaspuldaro) [reply packages/pipeline-editor/style/index.css:183]: I just followed what lab uses for dialogs, like `.jp-Dialog-content`

File: packages/pipeline-editor/src/PipelineExportDialog.tsx [hunk 3]
```diff
@@ -18,6 +18,8 @@ import * as React from 'react';
 
 import { IRuntime } from './PipelineService';
 
+import '../style/index.css';
```
Comment (ajbozarth) [inline packages/pipeline-editor/src/PipelineExportDialog.tsx:21]: this import isn't needed, the style sheet is imported in `index.ts` already

File: packages/pipeline-editor/src/NotebookSubmissionDialog.tsx [hunk 4]
```diff
@@ -20,6 +20,8 @@ import * as React from 'react';
 import { IRuntime } from './PipelineService';
 import Utils from './utils';
 
+import '../style/index.css';
```
Comment (ajbozarth) [inline packages/pipeline-editor/src/NotebookSubmissionDialog.tsx:23]: this import isn't needed, the style sheet is imported in `index.ts` already

**Comment by ajbozarth** [comment]
code-wise this LGTM, but I didn't have time to test locally

**Review by lresende — APPROVED** [review]
